apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-upgrade
  labels:
    app: k8s-app-upgrade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-app-upgrade
  template:
    metadata:
      labels:
        app: k8s-app-upgrade
    spec:
      containers:
      - name: k8s-app-upgrade
        image: k8s-app-upgrade:1.1
        ports:
        - containerPort: 8200
        readinessProbe:
          httpGet:
            path: ?delay=1
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: ?delay=1
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 60
          periodSeconds: 30