apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-upgrade
  labels:
    app: k8s-app-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app-upgrade
  template:
    metadata:
      labels:
        app: k8s-app-upgrade
    spec:
      containers:
      - name: k8s-app-upgrade
        image: jzwzz/k8s-app-upgrade:1.3.0
        ports:
        - containerPort: 8200
        readinessProbe:
          httpGet:
            path: /
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 60
          periodSeconds: 30